name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html-validator-action@v1
        with:
          path: "."

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."  # Upload all files from the root directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
